### ISSUE TITLE
ISSUE:  thread source out 

### ISSUE THREAD

**Issue by PoodleWang** [salesforce/jaxformer#5]
https://github.com/salesforce/jaxformer/blob/b8b389493b7c641a1d38bbec1b590d9eed3ff3be/preprocess/5_shuffe_concat_eos.py#L67

Hi, this code:  len(files) will burn out all threads.  Normally the machine has 80,000 threads. But one bucket's file length might be really huge. You can change this to args.works_num

**Comment by enijkamp** [comment]
Yes, changed. Thanks!
